# Generated by Django 4.1.5 on 2023-02-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience',
            new_name='EducationModel',
        ),
        migrations.RenameModel(
            old_name='Education',
            new_name='ExperienceModel',
        ),
        migrations.RenameModel(
            old_name='Information',
            new_name='InformationModel',
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageModel',
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='ProjectModel',
        ),
        migrations.RenameModel(
            old_name='Skillset',
            new_name='SkillsetModel',
        ),
    ]
